web:
 image: nginx:latest
 ports:
   - "8080:80"
 volumes:
   - ./web:/usr/share/nginx/html/
   - ./config/nginx.conf:/etc/nginx/conf.d/site.conf
 links:
   - php
php:
 image: php:7-fpm
 volumes:
    - ./web:/usr/share/nginx/html/
 links:
    - mysql
mysql:
  image: mysql:latest
  volumes:
    - ./db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
    - "3307:3306"
  restart: always
